# config/packages/messenger.yaml
framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}

        transports:
            # For sending OrderCreatedMessage to Products
            orders_out:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'orders'
                        type: topic

            # For receiving responses from Products
            orders_in:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'orders_responses'
                        type: topic
                    queues:
                        orders_responses_queue:
                            binding_keys: 
                                - 'order.validated'
                                - 'order.cancelled'

            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            # Outgoing messages
            App\Message\OrderCreatedMessage: orders_out
            
            # Incoming response messages
            App\Message\OrderValidatedMessage: orders_in
            App\Message\OrderCancelledMessage: orders_in

        buses:
            messenger.bus.default:
                default_middleware: true

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
